# Flake outputs entry point
# This file is referenced by the auto-generated flake.nix
inputs:
let
  inherit (inputs)
    nixpkgs
    flake-parts
    imp
    ;
in
flake-parts.lib.mkFlake { inherit inputs; } {
  imports = [
    imp.flakeModules.default
  ];

  systems = import inputs.systems;

  # imp configuration
  imp = {
    src = ../outputs;

    # Extra args available in all output files
    args = {
      inherit nixpkgs;
      rootSrc = ../..;
      # Pass inputs needed by formatter/checks
      treefmt-nix = inputs.treefmt-nix;
      imp-fmt-lib = inputs.imp-fmt.lib;
    };

    # Disable exports (not used in this project)
    exports.enable = false;

    # Auto-generate flake.nix from __inputs declarations
    flakeFile = {
      enable = true;
      coreInputs = import ./inputs.nix;
      description = "OpenCode Modules Plugin";
      outputsFile = "./nix/flake";
      header = ''
        # Auto-generated by imp - DO NOT EDIT
        # Regenerate with: nix run .#imp-flake
      '';
    };
  };
}
